= Why not Alacritty?

I loved Alacritty on Mac for years, but in 2024 it has fallen way behind and contains substantial, show-stopping bugs that make it absolutely unusable for me.

[TIP]
====
I am so glad https://twitch.tv/s9tpepper_[`s9tpepper_`] from Twitch shared with me why he prefers Wezterm (which has its own section now in https://rwxrob.github.io/books/terminal-velocity[_Terminal Velocity_]. (Even that italic that I just wrote for that title showed up beautifully, as does actual bold fonts. Wezterm is just so superior to Alacritty there isn't even a comparison at this point.
====

== No support for `Control-[`

While testing it on Windows I noticed a bunch of `[` showing up on the screen using the terminal the same was I have for more than 25 years. This turns out to be because Alacritty has a bug that does not observe the standard `Control-[` as `Esc`. If nothing else were wrong this would be enough for me to never use it again.

== Frequent, unexplained crashes

Last week while working on this book and trying to standardize on Alacritty (eventually going with Wezterm instead). Alacritty crashed without explanation or error at least a dozen times. I wasn't doing anything fancy. At least it was a good reminder why to write about tmux saving the day by being able to reattach after restarting.

== TOML configuration

I absolutely hate that Alacritty _forces_ me to use TOML for configuration for now good reason at all even though it quietly supports YAML still.

_(See <<why-not-toml, Why Not TOML>>.)_

== Impossibly poor emoji support

Want to use your favorite emoji with the emoji picker on a Mac? Tough. Alacritty doesn't support pasting them inline like every other terminal on the planet.

== Failure to implement all ANSI terminal escapes

I abandoned Alacritty once already in 2021 when I realized that some of the terminal animation and coloring using popular ANSI escapes wasn't supported. While I think that is supported now, the fact that it didn't work and now `Control-[` isn't supported suggests the team is not too keen on supporting the actual ANSI standards. All the other major terminals definitely do.

== No italic and true bold support

I have waited most of my life for a proper terminal to support thin and think text in the same font. Alacritty doesn't, most of the other modern ones do, including Windows Terminal Preview. That's right, Windows Terminal Preview is _better_ than Alacritty and every bit as fast.

== Speed

It took using Wezterm for a day or two to realize just how much I was needlessly suffering with terminal display lag on Alacritty. With things like pop-up completion options and such that lag is noticeable and annoying. Such is simply not an issue in all the others. Alacritty can't even compare and increasing speed on that level is not something Alacritty will ever be able to catch up with since it is a core implementation thing. They'd have to rewrite the entire engine.
